apiVersion: v1
kind: Service
metadata:
  name: springboot-movieland
  annotations:
    cloud.google.com/neg: '{"exposed_ports": {"8801":{}}}'
spec:
  type: LoadBalancer
  selector:
    app: springboot-movieland
  ports:
    - port: 8801
      protocol: TCP
      targetPort: 8801
---	  
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-movieland-deployment
  labels:
    app: springboot-movieland
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-movieland
  template:
    metadata:
      labels:
        app: springboot-movieland
    spec:
      containers:
      - name: movieland-rest
        image: afvillegas86/movieland-rest:1.0.0.1
        imagePullPolicy: IfNotPresent
        env:
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:mysql://mysql:3306/movielandDB"
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: mysql-database-username
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: mysql-database-password
        ports:
        - containerPort: 8801
