apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  mysql-root-password: cDBjS3ViM3JuM3QzczRkbTFuREI=
  mysql-database-username: bW92aWVsYW5kQXBwVXNlcg==
  mysql-database-password: bTB2MTNsNG5kMSo=
  mysql-database-name: bW92aWVsYW5kREI=