apiVersion: v1
kind: Service
metadata:
  name: mysql
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: LoadBalancer
  selector:
    app: mysql
  ports:
    - name: http
      protocol: TCP
      port: 3306
      targetPort: 3306
      
---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mysql
  annotations:
    dev.okteto.com/generate-host: mysql
spec:
  rules:
  - http:
      paths:
      - backend:
          service:
            name: mysql
            port:
              number: 3306
        path: /
        pathType: ImplementationSpecific
      
---	  
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      volumes:
      - name: mysql-pv-volume
        persistentVolumeClaim:
          claimName: mysql-pv-claim
      containers:
      - name: mysql
        image: mysql:5.6
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: mysql-root-password
        volumeMounts:
        - name: mysql-pv-volume
          mountPath: /var/lib/mysql
        ports:
        - containerPort: 3306
          name: mysql
